### ISSUE TITLE
'Runner' object has no attribute 'model_builder'

### ISSUE THREAD

**Issue by Xianqi-Zhang** [jiemingcui/anyskill#9]
Hi,

Command:
```
python calm/run.py --test --task HumanoidAMPGetup --num_envs 4 --cfg_env calm/data/cfg/humanoid.yaml --cfg_train calm/data/cfg/train/rlg/calm_humanoid.yaml --motion_file motions/motions_155.yaml --checkpoint ./Humanoid_00014500.pth
```

Output:
```
Setting seed: 1933
Traceback (most recent call last):
  File "calm/run.py", line 265, in <module>
    main()
  File "calm/run.py", line 256, in main
    runner = build_alg_runner(algo_observer)
  File "calm/run.py", line 169, in build_alg_runner
    runner.model_builder.model_factory.register_builder('amp', lambda network, **kwargs: amp_models.ModelAMPContinuous(network))
AttributeError: 'Runner' object has no attribute 'model_builder'
```

Thank u for any reply.

**Comment by jiemingcui** [comment]
It might be helpful to check the installation of IsaacGYM 🔢
